import { 
  cadeomw_body_pt, 
  ceia_body_pt, 
  deeplearningai_body_pt, 
  p4g_body_pt, 
  pibic_body_pt, 
  relatus_body_pt, 
} from './utils/pt_bodies';
import { 
  cadeomw_body_en, 
  ceia_body_en, 
  deeplearningai_body_en, 
  p4g_body_en, 
  pibic_body_en, 
  relatus_body_en, 
} from './utils/en_bodies';

export const ingles = {
  "language": "en",
  "titulo": "Software Engineer and Artificial Intelligence Enthusiast",
  "aboutMe": {
    "titulo": "About Me",
    "first_text_strong": "Hi! I'm Bruna Azambuja",
    "first_text": " and through this page you can learn a little more about me. I'm Brazilian, born and raised in Brasília. I'm 24 years old at the time (2024) and I have a degree in Computer Engineering from the University of Brasília - UnB. I have a high sense of organization and motivation to learn, as well as a high degree of commitment and responsibility. ",
    "second_text": "I am passionate about Artificial Intelligence and Computer Vision, and I intend, through computing, to defend and encourage women and girls in this area.",
    "info_pessoais": {
      "titulo": "Personal Information",
      "graduação_strong": "University graduate",
      "graduação": "Computer Engineering - UnB",
      "nascimento_strong": "Birth Date",
      "nascimento": "01/07/2000",
      "email_strong": "E-mail",
      "email": "brunazambuja@outlook.com",
      "nacionalidade_strong": "Nationality",
      "nacionalidade": "Brazilian - Brasília/DF",
      "status_strong": "Current Role",
      "status": "Mid Fullstack Engineer at Hinge Health",
    },
    "interesses": {
      "titulo": "Interests",
      "volei": "VOLLEY",
      "futevolei": "FOOTVOLLEY",
      "viajar": "TRAVEL",
      "musica": "MUSIC",
      "ia": "ARTIFICIAL INTELLIGENCE",
      "vc": "COMPUTER VISION",
      "social": "SOCIAL CONSCIENCE",
    }
  },
  "skills": {
    "dedication": "Dedication",
    "fast_learn": "Fast Learning", 
    "organization": "Organization",
    "communication": "Communication",
  },
  "resume": {
    "titulo": "Experiences",
    "graduated_unb": "Graduated in Computer Engineering",
    "unb": "University of Brasilia - 2022 Class",
    "destaque": "Outstanding Honorary Certificate",
    "cambridge": "Cambridge Degree:",
    "vobys": "Java Junior Intern",
    "ynvisto_ari": "Freelancer React Js",
    "pibic": "Research Assistant",
    "pibic_honor": "Honorable Mention",
    "gloria_micsft": "Software Engineer",
    "tukey": "Fullstack Developer and TechLead",
    "li": "Automation Engineer - QA",
    "hh": "Mid Fullstack Engineer",
    "atualmente": "currently",
  },
  "portfolio": {
    "titulo": "Portfolio",
    "relatus": "RELATUS - partnership with Microsoft",
    "ceia": "Center of Excellence in Artificial Intelligence",
    "pibic": "Scientific Initiation Project - Applied Studies in Computer Vision",
    "cadeomw_body": cadeomw_body_en,
    "ceia_body": ceia_body_en,
    "deeplearningai_body": deeplearningai_body_en,
    "p4g_body": p4g_body_en,
    "pibic_body": pibic_body_en,
    "relatus_body": relatus_body_en,
  }
}

export const portugues = {
  "language": "pt",
  "titulo": "Engenheira de Software e Entusiasta de Inteligência Artificial",
  "aboutMe": {
    "titulo": "Sobre mim",
    "first_text_strong": "Olá! Eu sou Bruna Azambuja",
    "first_text": " e por meio desta página você vai poder conhecer um pouquinho mais sobre mim. Sou brasileira, nascida e criada em Brasília. Tenho 24 anos no momento (2024) e sou formada em Engenharia de Computação pela Universidade de Brasília - UnB. Possuo um elevado senso de organização e motivação para aprender, assim como um alto grau de comprometimento e responsabilidade. ",
    "second_text": "Sou apaixonada por Inteligência Artificial e Visão Computacional, e pretendo, por meio da computação, defender e incentivar mulheres e meninas nesta área.",
    "info_pessoais": {
      "titulo": "Informações Pessoais",
      "graduação_strong": "Graduação",
      "graduação": "Engenharia da Computação - UnB",
      "nascimento_strong": "Data de Nascimento",
      "nascimento": "01/07/2000",
      "email_strong": "E-mail",
      "email": "brunazambuja@outlook.com",
      "nacionalidade_strong": "Nacionalidade",
      "nacionalidade": "Brasileira - Brasília/DF",
      "status_strong": "Cargo Atual",
      "status": "Engenheira Fullstack da Hinge Health",
    },
    "interesses": {
      "titulo": "Meus Interesses",
      "volei": "VÔLEI",
      "futevolei": "FUTVÔLEI",
      "viajar": "VIAJAR",
      "musica": "MÚSICA",
      "ia": "INTELIGÊNCIA ARTIFICIAL",
      "vc": "VISÃO COMPUTACIONAL",
      "social": "CONSCIÊNCIA SOCIAL",
    }
  },
  "skills": {
    "dedication": "Dedicação",
    "fast_learn": "Aprendizado Rápido",
    "organization": "Organização",
    "communication": "Comunicação",
  },
  "resume": {
    "titulo": "Experiências",
    "graduated_unb": "Formada em Engenharia de Computação",
    "unb": "Universidade de Brasilia - Turma de 2022",
    "destaque": "Certificado de Aluna Destaque",
    "cambridge": "Diploma de Cambridge:",
    "vobys": "Estagiária Java Júnior",
    "ynvisto_ari": "Freelancer React Js",
    "pibic": "Auxiliar de Pesquisa",
    "pibic_honor": "com Menção Honrosa",
    "gloria_micsft": "Engenheira de Software",
    "tukey": "Desenvolvedora Fullstack e TechLead",
    "li": "Engenheira de Automação - QA",
    "hh": "Engenheira Fullstack",
    "atualmente": "atualmente",
  },
  "portfolio": {
    "titulo": "Portfólio",
    "relatus": "RELATUS - parceria com Microsoft",
    "ceia": "Centro de Excelência em Inteligência Artificial",
    "pibic": "PIBIC - Estudos Aplicados em Visão Computacional",
    "cadeomw_body": cadeomw_body_pt,
    "ceia_body": ceia_body_pt,
    "deeplearningai_body": deeplearningai_body_pt,
    "p4g_body": p4g_body_pt,
    "pibic_body": pibic_body_pt,
    "relatus_body": relatus_body_pt,
  }
}
