
export const ingles = {
  "titulo": "Software Engineer and Artificial Intelligence Enthusiast",
  "aboutMe": {
    "titulo": "About Me",
    "first_text_strong": "Hi! I'm Bruna Azambuja",
    "first_text": " and through this page you can learn a little more about me. I'm Brazilian, born and raised in Brasília. I'm 22 years old at the time (2022) and I have a degree in Computer Engineering from the University of Brasília - UnB. I have a high sense of organization and motivation to learn, as well as a high degree of commitment and responsibility. ",
    "second_text": "I'm passionate about playing volleyball and I'm begining to learn footvolley. I am an Artificial Intelligence and Computer Vision enthusiast, and I intend, through computing, to defend and encourage women and girls in this area.",
    "info_pessoais": {
      "titulo": "Personal Information",
      "graduação_strong": "University graduate",
      "graduação": "Computer Engineering - UnB",
      "nascimento_strong": "Birth Date",
      "nascimento": "01/07/2000",
      "email_strong": "E-mail",
      "email": "brunazambuja@outlook.com",
      "nacionalidade_strong": "Nationality",
      "nacionalidade": "Brazilian - Brasília/DF",
      "status_strong": "Part Time",
      "status": "Fullstack Developer at Tukey Data",
      "status2_strong": "Full Time",
      "status2": "Automation QA at Loja Integrada",
    },
    "interesses": {
      "titulo": "Interests",
      "volei": "VOLLEY",
      "futevolei": "FOOTVOLLEY",
      "viajar": "TRAVEL",
      "musica": "MUSIC",
      "ia": "ARTIFICIAL INTELLIGENCE",
      "vc": "COMPUTER VISION",
      "social": "SOCIAL CONSCIENCE",
    }
  },
  "skills": {
    "dedication": "Dedication",
    "fast_learn": "Fast Learning", 
    "organization": "Organization",
    "communication": "Communication",
  },
  "resume": {
    "unb": "Graduated in Computer Engineering - UnB",
    "cambridge": "Cambridge Degree:",
    "vobys": "Java Junior Intern",
    "ynvisto_ari": "Freelancer React Js",
    "pibic": "Research Assistant",
    "pibic_honor": "Honorable Mention",
    "gloria_micsft": "Software Engineer",
    "tukey": "Fullstack Developer and TechLead",
    "li": "Automation Engineer - QA",
    "atualmente": "currently",
  },
}

export const portugues = {
  "titulo": "Engenheira de Software e Entusiasta de Inteligência Artificial",
  "aboutMe": {
    "titulo": "Sobre mim",
    "first_text_strong": "Olá! Eu sou Bruna Azambuja",
    "first_text": " e por meio desta página você vai poder conhecer um pouquinho mais sobre mim. Sou brasileira, nascida e criada em Brasília. Tenho 22 anos no momento (2022) e sou formada em Engenharia de Computação pela Universidade de Brasília - UnB. Possuo um elevado senso de organização e motivação para aprender, assim como um alto grau de comprometimento e responsabilidade. ",
    "second_text": "Sou apaixonada por jogar volêi e estou me aventurando no Futvôlei. Sou entusiasta de Inteligência Artificial e Visão Computacional, e pretendo, por meio da computação, defender e incentivar mulheres e meninas nesta área.",
    "info_pessoais": {
      "titulo": "Informações Pessoais",
      "graduação_strong": "Graduação",
      "graduação": "Engenharia da Computação - UnB",
      "nascimento_strong": "Data de Nascimento",
      "nascimento": "01/07/2000",
      "email_strong": "E-mail",
      "email": "brunazambuja@outlook.com",
      "nacionalidade_strong": "Nacionalidade",
      "nacionalidade": "Brasileira - Brasília/DF",
      "status_strong": "Meio Período",
      "status": "Desenvolvedora Fullstack da Tukey Data",
      "status2_strong": "Efetivada",
      "status2": "QA de Automação na Loja Integrada",
    },
    "interesses": {
      "titulo": "Meus Interesses",
      "volei": "VÔLEI",
      "futevolei": "FUTVÔLEI",
      "viajar": "VIAJAR",
      "musica": "MÚSICA",
      "ia": "INTELIGÊNCIA ARTIFICIAL",
      "vc": "VISÃO COMPUTACIONAL",
      "social": "CONSCIÊNCIA SOCIAL",
    }
  },
  "skills": {
    "dedication": "Dedicação",
    "fast_learn": "Aprendizado Rápido",
    "organization": "Organização",
    "communication": "Comunicação",
  },
  "resume": {
    "unb": "Formada em Engenharia de Computação - UnB",
    "cambridge": "Diploma de Cambridge:",
    "vobys": "Estagiária Java Júnior",
    "ynvisto_ari": "Freelancer React Js",
    "pibic": "Auxiliar de Pesquisa",
    "pibic_honor": "com Menção Honrosa",
    "gloria_micsft": "Engenheira de Software",
    "tukey": "Desenvolvedora Fullstack e TechLead",
    "li": "Engenheira de Automação - QA",
    "atualmente": "atualmente",
  },
}
